grails-app/domain/ie/koala/dontforget/Reminder.groovy
package ie.koala.dontforget

class Reminder {
	
	String description
	Date dateCreated
	boolean checked

	static belongsTo = [user: User]
	
    static constraints = {
		description blank: false, size:0..65535, widget: 'textarea'
    }

}

grails-app/domain/ie/koala/dontforget/Role.groovy
package ie.koala.dontforget

class Role {

	String authority

	static mapping = {
		cache true
	}

	static constraints = {
		authority blank: false, unique: true
	}
}

grails-app/domain/ie/koala/dontforget/User.groovy
package ie.koala.dontforget

class User {

	def springSecurityService

	String username
	String password
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired
	
	static hasMany = [reminders: Reminder]

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
		reminders sort: 'dateCreated'
	}

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role } as Set
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService.encodePassword(password)
	}
	
	String toString() {
		return username
	}
}

grails-app/domain/ie/koala/dontforget/UserRole.groovy
package ie.koala.dontforget

import org.apache.commons.lang.builder.HashCodeBuilder

class UserRole implements Serializable {

	private static final long serialVersionUID = 1

	User user
	Role role

	boolean equals(other) {
		if (!(other instanceof UserRole)) {
			return false
		}

		other.user?.id == user?.id &&
			other.role?.id == role?.id
	}

	int hashCode() {
		def builder = new HashCodeBuilder()
		if (user) builder.append(user.id)
		if (role) builder.append(role.id)
		builder.toHashCode()
	}

	static UserRole get(long userId, long roleId) {
		UserRole.where {
			user == User.load(userId) &&
			role == Role.load(roleId)
		}.get()
	}

	static UserRole create(User user, Role role, boolean flush = false) {
		new UserRole(user: user, role: role).save(flush: flush, insert: true)
	}

	static boolean remove(User u, Role r, boolean flush = false) {

		int rowCount = UserRole.where {
			user == User.load(u.id) &&
			role == Role.load(r.id)
		}.deleteAll()

		rowCount > 0
	}

	static void removeAll(User u) {
		UserRole.where {
			user == User.load(u.id)
		}.deleteAll()
	}

	static void removeAll(Role r) {
		UserRole.where {
			role == Role.load(r.id)
		}.deleteAll()
	}

	static mapping = {
		id composite: ['role', 'user']
		version false
	}
}

grails-app/controllers/ie/koala/dontforget/InfoController.groovy
package ie.koala.dontforget

import grails.plugin.springsecurity.annotation.Secured

@Secured(['IS_AUTHENTICATED_ANONYMOUSLY'])
class InfoController {
	
	def learn() { }
	
	def contact() { }

    def about() { }
}

grails-app/controllers/ie/koala/dontforget/ReminderController.groovy
package ie.koala.dontforget

import org.springframework.dao.DataIntegrityViolationException
import grails.plugin.springsecurity.annotation.Secured
import grails.plugin.springsecurity.SpringSecurityUtils

@Secured(['ROLE_USER', 'ROLE_ADMIN'])
class ReminderController {

	static allowedMethods = [create: ['GET', 'POST'], edit: ['GET', 'POST'], delete: 'POST']

	def springSecurityService

	def index() {
		redirect action: 'list', params: params
	}

	def list() {
		List<Reminder> list
		int count

		User user = springSecurityService.currentUser
		boolean isAdmin = SpringSecurityUtils.ifAllGranted('ROLE_ADMIN')
		log.debug "user=${user} isAdmin=${isAdmin}"

		params.max = Math.min(params.max ? params.int('max') : 10, 100)
		if (isAdmin) {
			list = Reminder.list(params)
			count = Reminder.count()
		} else {
			list = Reminder.findAllByUser(user, params)
			count = list.size()
		}
		[reminderInstanceList: list, reminderInstanceTotal: count]
	}

	def create() {
		User user = springSecurityService.currentUser
		boolean isAdmin = SpringSecurityUtils.ifAllGranted('ROLE_ADMIN')
		log.debug "user=${user} isAdmin=${isAdmin}"

		switch (request.method) {
			case 'GET':
				[reminderInstance: new Reminder(params)]
				break
			case 'POST':
				def reminderInstance
				if (isAdmin) {
					reminderInstance = new Reminder(params)
				} else {
					reminderInstance = new Reminder(user: user)
					bindData(reminderInstance, params, [exclude: ['user']])
				}
				if (!reminderInstance.save(flush: true)) {
					render view: 'create', model: [reminderInstance: reminderInstance]
					return
				}

				flash.message = message(code: 'default.created.message', args: [
					message(code: 'reminder.label', default: 'Reminder'),
					reminderInstance.id
				])
				redirect action: 'show', id: reminderInstance.id
				break
		}
	}

	def show() {
		User user = springSecurityService.currentUser
		boolean isAdmin = SpringSecurityUtils.ifAllGranted('ROLE_ADMIN')
		log.debug "user=${user} isAdmin=${isAdmin}"

		def reminderInstance
		if (isAdmin) {
			reminderInstance = Reminder.get(params.id)
		} else {
			reminderInstance = Reminder.findWhere(user: user, id: params.long('id'))
		}
		if (!reminderInstance) {
			flash.message = message(code: 'default.not.found.message', args: [
				message(code: 'reminder.label', default: 'Reminder'),
				params.id
			])
			redirect action: 'list'
			return
		}

		[reminderInstance: reminderInstance]
	}

	def edit() {
		User user = springSecurityService.currentUser
		boolean isAdmin = SpringSecurityUtils.ifAllGranted('ROLE_ADMIN')
		log.debug "user=${user} isAdmin=${isAdmin}"

		def reminderInstance
		if (isAdmin) {
			reminderInstance = Reminder.get(params.id)
		} else {
			reminderInstance = Reminder.findWhere(user: user, id: params.long('id'))
		}
		switch (request.method) {
			case 'GET':
				if (!reminderInstance) {
					flash.message = message(code: 'default.not.found.message', args: [
						message(code: 'reminder.label', default: 'Reminder'),
						params.id
					])
					redirect action: 'list'
					return
				}

				[reminderInstance: reminderInstance]
				break
			case 'POST':
				if (!reminderInstance) {
					flash.message = message(code: 'default.not.found.message', args: [
						message(code: 'reminder.label', default: 'Reminder'),
						params.id
					])
					redirect action: 'list'
					return
				}

				if (params.version) {
					def version = params.version.toLong()
					if (reminderInstance.version > version) {
						reminderInstance.errors.rejectValue('version', 'default.optimistic.locking.failure',
								[
									message(code: 'reminder.label', default: 'Reminder')] as Object[],
								"Another user has updated this Reminder while you were editing")
						render view: 'edit', model: [reminderInstance: reminderInstance]
						return
					}
				}

				reminderInstance.properties = params

				if (!reminderInstance.save(flush: true)) {
					render view: 'edit', model: [reminderInstance: reminderInstance]
					return
				}

				flash.message = message(code: 'default.updated.message', args: [
					message(code: 'reminder.label', default: 'Reminder'),
					reminderInstance.id
				])
				redirect action: 'show', id: reminderInstance.id
				break
		}
	}

	def delete() {
		User user = springSecurityService.currentUser
		boolean isAdmin = SpringSecurityUtils.ifAllGranted('ROLE_ADMIN')
		log.debug "user=${user} isAdmin=${isAdmin}"

		def reminderInstance
		if (isAdmin) {
			reminderInstance = Reminder.get(params.id)
		} else {
			reminderInstance = Reminder.findWhere(user: user, id: params.long('id'))
		}
		if (!reminderInstance) {
			flash.message = message(code: 'default.not.found.message', args: [
				message(code: 'reminder.label', default: 'Reminder'),
				params.id
			])
			redirect action: 'list'
			return
		}

		try {
			reminderInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message', args: [
				message(code: 'reminder.label', default: 'Reminder'),
				params.id
			])
			redirect action: 'list'
		}
		catch (DataIntegrityViolationException e) {
			flash.message = message(code: 'default.not.deleted.message', args: [
				message(code: 'reminder.label', default: 'Reminder'),
				params.id
			])
			redirect action: 'show', id: params.id
		}
	}
}

grails-app/views/_fields/default/_field.gsp
<%@ page defaultCodec="html" %>
<div class="control-group ${invalid ? 'error' : ''}">
	<label class="control-label" for="${property}">${label}</label>
	<div class="controls">
		<%= widget %>
		<g:if test="${invalid}"><span class="help-inline">${errors.join('<br>')}</span></g:if>
	</div>
</div>

grails-app/views/_fields/localDate/_input.gsp
<%
	def attrs = [name: property, value: value, placeholder: 'yyyy-mm-dd', size: 10]
	if (required) attrs.required = ''
	out << joda.dateField(attrs)
%>

grails-app/views/info/about.gsp
<body>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<i class="icon-info-sign"></i> The Koala Computer Company Limited
					</h1>
				</div>
				<div class="padded">
					<p>We are an Irish IT consultancy company.</p>
					<p>We provide software development services to a number of
						clients, both in Ireland and abroad.</p>
					<p>Areas of expertise and consultancy in the areas of</p>
					<ul>
						<li>Web software development</li>
						<li>Android software development</li>
						<li>Enterprise architecture</li>
						<li>Risk analysis</li>
						<li>Biometrics</li>
						<li>Business Intelligence</li>
					</ul>
					<p>For further details, please contact us.</p>
				</div>
			</div>
		</div>
	</div>
</body>

grails-app/views/info/contact.gsp
<body>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<i class="icon-info-sign"></i> Contact Information
					</h1>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<div class="well">
					<div class="padded">
						<p>
							<strong>The Koala Computer Company Limited</strong> <br /> 10
							Castle Avenue <br /> Clontarf <br /> Dublin 3 <br /> Ireland <br />
						</p>
						<p>
							<strong>Phone</abbr></strong> +353 1 805 70035
						</p>
						<p>
							<strong>Email</strong> <a href="mailto:info@koala.ie">info@koala.ie</a>
						</p>
					</div>
				</div>
			</div>
			<div class="col-lg-8">
				<div class="well">
					<div class="padded">
						<iframe width="100%" scrolling="no" height="300" frameborder="0"
							src="https://www.google.com/maps?q=10+Castle+Ave,+Dublin+3,+Ireland&t=m&hnear=10+Castle+Ave,+Dublin+3,+County+Dublin,+Ireland&z=16&iwloc=near&output=embed"
							marginwidth="0" marginheight="0"></iframe>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

grails-app/views/info/learn.gsp
<body>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<i class="icon-info-sign"></i> Learn more about Please Remember,
						Don't Forget
					</h1>
				</div>
				<div class="padded">
					<p>This is where there will be some additional information
						about the program.</p>
					<ul>
						<li>Users can sign in using a unique login and password.</li>
						<li>Users can view their current task list</li>
						<li>Users can check and uncheck any task on their list</li>
						<li>Users can add and remove tasks</li>
						<li>All changes are persistent. When a user signs into the
							system next time they will see changes made during previous
							session.</li>
						<li>Each 'task' contains a text description and date when the
							entry was created.</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</body>

grails-app/views/layouts/application.gsp
<%@ page
	import="org.codehaus.groovy.grails.web.servlet.GrailsApplicationAttributes"%>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><g:layoutTitle default="${meta(name: 'app.name')}" /></title>
<meta name="description"
	content="Please remember, don't forget. A website for to-do lists.">
<meta name="author" content="The Koala Computer Company Limited">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<r:require modules="application" />
<g:layoutHead />
<r:layoutResources />
</head>

<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<sec:ifNotLoggedIn>
					<a class="navbar-brand" href="${createLink(uri: '/')}">
						${meta(name: 'app.name')}
					</a>
				</sec:ifNotLoggedIn>
				<sec:ifLoggedIn>
					<g:link controller="reminder" action="list" class="navbar-brand" >${meta(name: 'app.name')}</g:link>
				</sec:ifLoggedIn>

			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav"><%--
					<sec:ifLoggedIn>
						<li><g:link controller="reminder" action="list">Reminder</g:link></li>
					</sec:ifLoggedIn>
					--%><li class="dropdown"><a href="#" class="dropdown-toggle"
						data-toggle="dropdown">Menu <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><g:link controller="info" action="about">About Koala</g:link></li>
							<li><g:link controller="info" action="learn">About dontforget</g:link></li>
							<li><g:link controller="info" action="contact">Contact</g:link></li>
							<sec:ifLoggedIn>
								<li class="divider"></li>
								<li><g:link controller="logout">Sign out <sec:username /></g:link></li>
							</sec:ifLoggedIn>
						</ul></li>
				</ul>
				<sec:ifNotLoggedIn>
					<g:form uri="/j_spring_security_check"
						class="navbar-form navbar-right">
						<div class="form-group">
							<input type="text" placeholder="Username" class="form-control"
								name='j_username' id='username' />
						</div>
						<div class="form-group">
							<input type="password" placeholder="Password"
								class="form-control" name='j_password' id='password' />
						</div>
						<button type="submit" class="btn btn-success">Sign in</button>
					</g:form>
				</sec:ifNotLoggedIn>
				<sec:ifLoggedIn>
					<g:form uri="/j_spring_security_logout" method="POST"
						class="navbar-form navbar-right">
						<button type="submit" class="btn btn-success">Sign out <sec:username /></button>
					</g:form>
				</sec:ifLoggedIn>
			</div>
			<!--/.navbar-collapse -->
		</div>
	</div>
	<g:layoutBody />
	<div class="container">
		<div class="row">
			<hr>
			<footer>
				<p>Copyright &copy; 2013 The Koala Computer Company Limited</p>
			</footer>
		</div>
	</div>
	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push([ '_setAccount', 'UA-44752619-3' ]);
		_gaq.push([ '_trackPageview' ]);
		(function() {
			var ga = document.createElement('script');
			ga.type = 'text/javascript';
			ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl'
					: 'http://www')
					+ '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(ga, s);
		})();
	</script>
	<r:layoutResources />
</body>
</html>

grails-app/views/login/auth.gsp
<body>
    <div class='container'>
            <div class="row">
                <legend><g:message code="springSecurity.login.header"/></legend>
                <div class="col-lg-6">
            <g:if test='${flash.message}'>
                <div class='alert alert-error'>${flash.message}</div>
            </g:if>
                    <form action='${postUrl}' method='POST' id='loginForm' class='form-horizontal' autocomplete='off'>
                        <div class="control-group">
                            <label class="control-label" for='username'><g:message code="springSecurity.login.username.label"/>:</label>
                            <div class="controls">
                                <input type='text' class='text_' name='j_username' id='username'/>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for='password'><g:message code="springSecurity.login.password.label"/>:</label>
                            <div class="controls">
                                <input type='password' class='text_' name='j_password' id='password'/>
                            </div>
                        </div>
                        <div class="control-group" id="remember_me_holder">
                            <div class="controls">
                                <label class="checkbox" for='remember_me'><g:message code="springSecurity.login.remember.me.label"/>
                                    <input type='checkbox' name='${rememberMeParameter}' id='remember_me'
                                           <g:if test='${hasCookie}'>checked='checked'</g:if>/>
                                </label>
                                <input class="btn btn-primary" type='submit' id="submit" value='${message(code: "springSecurity.login.button")}'/>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6">
                    <div class="well">
                    	<p>For this demo, please use one of the following accounts:</p>
                        <dl class="dl-horizontal">
                            <dt>Admin User:</dt>
                            <dd>admin/adm1n</dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Guest User:</dt>
                            <dd>test/abc123</dd>
                        </dl>
                    </div>
                </div>
            </div>
    </div>
</body>
</html>

grails-app/views/login/denied.gsp
<body>
    <div class='container'>
        <div class='alert alert-block alert-error'>
            <g:message code="springSecurity.denied.message" />
            <br/><br/>
            <g:link class="btn btn-inverse" uri="/">Return Home</g:link>
        </div>
    </div>
</body>

grails-app/views/reminder/_form.gsp
<%@ page import="ie.koala.dontforget.Reminder" %>



<div class="fieldcontain ${hasErrors(bean: reminderInstance, field: 'description', 'error')} required">
	<label for="description">
		<g:message code="reminder.description.label" default="Description" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="description" required="" value="${reminderInstance?.description}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: reminderInstance, field: 'user', 'error')} required">
	<label for="user">
		<g:message code="reminder.user.label" default="User" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="user" name="user.id" from="${ie.koala.dontforget.User.list()}" optionKey="id" required="" value="${reminderInstance?.user?.id}" class="many-to-one"/>
</div>

grails-app/views/reminder/checked/_field.gsp
<div class="form-group">
	<label class="col-lg-2 control-label" for="checked"> <g:message
			code="reminder.checked.label" default="Checked" /></label>
	<div class="col-lg-10">
		<g:field type="hidden" name="_checked" />
		<g:checkBox class="form-control" name="checked" id="checked"
			value="${bean?.checked}" />
	</div>
</div>

grails-app/views/reminder/create.gsp
<%@ page import="ie.koala.dontforget.Reminder" %>
<!doctype html>
<html>
<head>
<meta name="layout" content="application">
<g:set var="entityName"
	value="${message(code: 'reminder.label', default: 'Reminder')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<div class="container">
		<div class="row">

			<div class="col-lg-3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li><g:link class="list" action="list">
								<i class="icon-list"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link></li>
						<li class="active"><g:link class="create" action="create">
								<i class="icon-plus icon-white"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link></li>
					</ul>
				</div>
			</div>

			<div class="col-lg-9">

				<div class="page-header">
					<h1>
						<g:message code="default.create.label" args="[entityName]" />
					</h1>
				</div>

				<g:if test="${flash.message}">
					<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>

				<g:hasErrors bean="${reminderInstance}">
					<bootstrap:alert class="alert-error">
						<ul>
							<g:eachError bean="${reminderInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</bootstrap:alert>
				</g:hasErrors>

				<fieldset>
					<g:form class="form-horizontal" action="create"
						>
						<fieldset>
					<f:field bean="reminderInstance" property="description">
						<g:textArea name="description" />
					</f:field>
					<f:field bean="reminderInstance" property="checked" />
					<sec:ifAllGranted roles="ROLE_ADMIN">
						<f:field bean="reminderInstance" property="user" />
					</sec:ifAllGranted>
							<div class="form-actions">
								<button type="submit" class="btn btn-primary">
									<i class="icon-ok icon-white"></i>
									<g:message code="default.button.create.label" default="Create" />
								</button>
							</div>
						</fieldset>
					</g:form>
				</fieldset>

			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/reminder/description/_field.gsp
<div class="form-group">
	<label class="col-lg-2 control-label" for="description"> <g:message
			code="reminder.description.label" default="Description" /></label>
	<div class="col-lg-10">
		<g:textArea class="form-control" name="description"
			id="description" rows="3">${bean?.description}</g:textArea>
	</div>
</div>

grails-app/views/reminder/edit.gsp
<%@ page import="ie.koala.dontforget.Reminder"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="application">
<g:set var="entityName"
	value="${message(code: 'reminder.label', default: 'Reminder')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
	<div class="container">
		<div class="row">

			<div class="col-lg-3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">
							${entityName}
						</li>
						<li><g:link class="list" action="list">
								<i class="icon-list"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link></li>
						<li><g:link class="create" action="create">
								<i class="icon-plus"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link></li>
					</ul>
				</div>
			</div>

			<div class="col-lg-9">

				<div class="page-header">
					<h1>
						<g:message code="default.edit.label" args="[entityName]" />
					</h1>
				</div>

				<g:if test="${flash.message}">
					<bootstrap:alert class="alert-info">
						${flash.message}
					</bootstrap:alert>
				</g:if>

				<g:hasErrors bean="${reminderInstance}">
					<bootstrap:alert class="alert-error">
						<ul>
							<g:eachError bean="${reminderInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</bootstrap:alert>
				</g:hasErrors>

				<g:form class="form-horizontal" action="edit"
					id="${reminderInstance?.id}">
					<g:hiddenField name="version" value="${reminderInstance?.version}" />
					<f:field bean="reminderInstance" property="description">
						<g:textArea name="description" />
					</f:field>
					<f:field bean="reminderInstance" property="checked" />
					<sec:ifAllGranted roles="ROLE_ADMIN">
						<f:field bean="reminderInstance" property="user" />
					</sec:ifAllGranted>
					<div class="form-actions">
						<button type="submit" class="btn btn-primary">
							<i class="icon-ok icon-white"></i>
							<g:message code="default.button.update.label" default="Update" />
						</button>
						<button type="submit" class="btn btn-danger" name="_action_delete"
							formnovalidate>
							<i class="icon-trash icon-white"></i>
							<g:message code="default.button.delete.label" default="Delete" />
						</button>
					</div>
				</g:form>
			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/reminder/list.gsp
<%@ page import="ie.koala.dontforget.Reminder"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="application">
<g:set var="entityName" value="${message(code: 'reminder.label', default: 'Reminder')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">
							${entityName}
						</li>
						<li class="active"><g:link class="list" action="list">
								<i class="icon-list icon-white"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link></li>
						<li><g:link class="create" action="create">
								<i class="icon-plus"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-9">
				<div class="page-header">
					<h1>
						<g:message code="default.list.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<bootstrap:alert class="alert-info">
						${flash.message}
					</bootstrap:alert>
				</g:if>
				<table class="table table-striped">
					<thead>
						<tr>
							<g:sortableColumn property="description"
								title="${message(code: 'reminder.description.label', default: 'Description')}" />
							<g:sortableColumn property="dateCreated"
								title="${message(code: 'reminder.dateCreated.label', default: 'Date Created')}" />
							<th class="header"><g:message code="reminder.checked.label"
									default="Checked" /></th>
							<sec:ifAllGranted roles="ROLE_ADMIN">
								<g:sortableColumn property="user"
									title="${message(code: 'reminder.user.label', default: 'User')}" />
							</sec:ifAllGranted>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<g:each in="${reminderInstanceList}" var="reminderInstance">
							<tr>
								<td>
									${fieldValue(bean: reminderInstance, field: "description")}
								</td>
								<td><g:formatDate date="${reminderInstance.dateCreated}" /></td>
								<td><g:formatBoolean boolean="${reminderInstance.checked}" /></td>
								<sec:ifAllGranted roles="ROLE_ADMIN">
									<td>
										${fieldValue(bean: reminderInstance, field: "user")}
									</td>
								</sec:ifAllGranted>
								<td class="link"><g:link action="show"
										id="${reminderInstance.id}" class="btn btn-primary">Show &raquo;</g:link>
								</td>
							</tr>
						</g:each>
					</tbody>
				</table>
				<div class="pagination">
					<bootstrap:paginate total="${reminderInstanceTotal}" />
				</div>
			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/reminder/user/_field.gsp
<%@ page import="ie.koala.dontforget.User" %>
<div class="form-group ">
	<label class="col-lg-2 control-label" for="user"> <g:message
			code="reminder.user.label" default="User" /></label>
	<div class="col-lg-10">
		<g:select class="form-control" name="user.id" from="${User.list()}" value="${bean?.id}"
			optionKey="id" />
	</div>
</div>